name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies (including dev)
        run: npm ci

      - name: Ensure clean workspace
        run: git clean -fdx || true

      - name: Show Node / npm / tsc versions
        run: node -v; npm -v; npx tsc -v || true

      - name: Build (clean + tsc + rollup)
        run: npm run build

      - name: Run tests (after build)
        run: npm test
